# -*- coding: utf-8 -*-
"""medical-text-summarization-t5-finetuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LY6QET7GCKwp8eLxasvmivY7puKOPK3n
"""

# -------------------------------------------------------------
# STEP 1: SETUP ENVIRONMENT & ASK FOR FILE UPLOAD
# -------------------------------------------------------------
!pip install transformers torch pandas numpy sentencepiece -q

import pandas as pd
import numpy as np
import os, zipfile
from google.colab import files
from sklearn.model_selection import train_test_split
from transformers import T5Tokenizer, T5ForConditionalGeneration, Trainer, TrainingArguments
from torch.utils.data import Dataset
import torch

print("📂 Please upload your dataset ZIP file (example: 123.zip or archive(1).zip)")
uploaded = files.upload()  # 👈 this will prompt file upload

# Automatically get uploaded filename
zip_filename = list(uploaded.keys())[0]
zip_path = f"/content/{zip_filename}"
extract_path = "/content/data"
os.makedirs(extract_path, exist_ok=True)

# -------------------------------------------------------------
# STEP 2: EXTRACT ZIP CONTENTS
# -------------------------------------------------------------
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ Dataset extracted to:", extract_path)
print("📁 Files inside extracted folder:", os.listdir(extract_path))

# -------------------------------------------------------------
# STEP 3: LOAD DATA
# -------------------------------------------------------------
# Adjust file name if different
file_path = os.path.join(extract_path, "mtsamples.csv")

if not os.path.exists(file_path):
    # Find any CSV inside folder
    for f in os.listdir(extract_path):
        if f.endswith(".csv"):
            file_path = os.path.join(extract_path, f)
            break

if not os.path.exists(file_path):
    raise FileNotFoundError("❌ Could not find any CSV file inside your zip. Please check contents.")

df = pd.read_csv(file_path)
print("✅ Data loaded successfully! Columns:", df.columns.tolist())
display(df.head())

# -------------------------------------------------------------
# STEP 4: PREPROCESS DATA
# -------------------------------------------------------------
# Rename if needed
if "transcription" in df.columns:
    df = df.rename(columns={"transcription": "input_text"})
elif "text" in df.columns:
    df = df.rename(columns={"text": "input_text"})
else:
    first_col = df.columns[0]
    df = df.rename(columns={first_col: "input_text"})

# Create target text
target_cols = []
if 'medical_specialty' in df.columns:
    target_cols.append('medical_specialty')
if 'keywords' in df.columns:
    target_cols.append('keywords')

if target_cols:
    df['target_text'] = df[target_cols].astype(str).agg(' - '.join, axis=1)
else:
    df['target_text'] = "General medical explanation"

# Add context prefix
df["input_text"] = "Transcription: " + df["input_text"].astype(str)
df["target_text"] = df["target_text"].astype(str)

# Clean nulls
df.dropna(subset=['input_text', 'target_text'], inplace=True)
df = df[(df['input_text'].str.strip() != '') & (df['target_text'].str.strip() != '')]

print("✅ Cleaned dataset shape:", df.shape)

# Split into train/validation
train_df, valid_df = train_test_split(df, test_size=0.1, random_state=42)
processed_data_dir = "/content/data/processed"
os.makedirs(processed_data_dir, exist_ok=True)
train_df.to_csv(os.path.join(processed_data_dir, "train.csv"), index=False)
valid_df.to_csv(os.path.join(processed_data_dir, "valid.csv"), index=False)
print(f"✅ Data saved: {len(train_df)} train samples, {len(valid_df)} validation samples")

# -------------------------------------------------------------
# STEP 5: LOAD MODEL AND TOKENIZER
# -------------------------------------------------------------
MODEL_NAME = "t5-small"  # lightweight for Colab
tokenizer = T5Tokenizer.from_pretrained(MODEL_NAME)
model = T5ForConditionalGeneration.from_pretrained(MODEL_NAME)

# -------------------------------------------------------------
# STEP 6: CREATE DATASET CLASS
# -------------------------------------------------------------
class MedicalTextDataset(Dataset):
    def __init__(self, data, tokenizer, max_len=256):
        self.data = data.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        input_text = str(self.data.loc[index, "input_text"])
        target_text = str(self.data.loc[index, "target_text"])

        source = self.tokenizer(
            input_text, max_length=self.max_len, padding="max_length",
            truncation=True, return_tensors="pt"
        )
        target = self.tokenizer(
            target_text, max_length=self.max_len, padding="max_length",
            truncation=True, return_tensors="pt"
        )

        labels = target["input_ids"].squeeze()
        labels[labels == self.tokenizer.pad_token_id] = -100

        return {
            "input_ids": source["input_ids"].squeeze(),
            "attention_mask": source["attention_mask"].squeeze(),
            "labels": labels,
        }

train_dataset = MedicalTextDataset(train_df, tokenizer)
valid_dataset = MedicalTextDataset(valid_df, tokenizer)

print(f"📊 Train dataset: {len(train_dataset)} samples")
print(f"📊 Validation dataset: {len(valid_dataset)} samples")

# -------------------------------------------------------------
# STEP 7: TRAINING CONFIG
# -------------------------------------------------------------
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,              # You can increase later
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    eval_strategy="epoch",
    logging_dir="./logs",
    logging_steps=50,
    save_total_limit=1,
    learning_rate=3e-4,
    report_to="none"
)

# -------------------------------------------------------------
# STEP 8: TRAIN THE MODEL
# -------------------------------------------------------------
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    tokenizer=tokenizer
)

print("🚀 Starting fine-tuning... This may take a few minutes.")
trainer.train()
print("✅ Training completed successfully!")

# -------------------------------------------------------------
# STEP 9: TEST THE MODEL
# -------------------------------------------------------------
test_input = "Transcription: Patient reports fever, headache, and mild cough for two days."
input_ids = tokenizer.encode(test_input, return_tensors="pt").to(model.device) # Move input to model device

outputs = model.generate(
    input_ids,
    max_length=80,
    num_beams=4,
    early_stopping=True
)

print("\n🩺 Model Explanation Output:")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))